name: Test source installation

on:
  schedule:
    - cron: |
        0 23 * * *
  push:
    paths:
      - '.github/workflows/test-source.yml'
      - 'linux/install-arrow.R'
  # On tag too?

jobs:
  source:
    name: Source packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v1
      - name: Install R
        uses: r-lib/actions/setup-r@master
      - name: Install arrow from bintray
        env:
          # Test source build so be sure not to download a binary
          LIBARROW_BINARY: "FALSE"
        run: Rscript linux/install-arrow.R
      - name: Retry with verbosity if that failed
        env:
          LIBARROW_BINARY: "FALSE"
          ARROW_R_DEV: "TRUE"
        run: Rscript linux/install-arrow.R
        if: failure()
